name: "Release"
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      gitHubWriteToken: ${{ secrets.gitHubWriteToken }}
      gitUserEmail: ${{ secrets.gitUserEmail }}
      gitUserName: ${{ secrets.gitUserName }}
      releaseGradleFlags: '--max-workers 1 -PSNAPSHOT=false -PLOCAL_UPLOAD=false -PRELEASE_BUILD_TYPE_ENABLED=true -PRELEASE_FAKE_ENABLED=true -PACCEPT_SNAPSHOT_DEPENDENCIES=false --stacktrace'
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.caching=true'
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Switch to Gradle Binary Distribution
        run: sed -i -e 's/-all.zip/-bin.zip/' gradle/wrapper/gradle-wrapper.properties

      - name: Close GitHub Milestone
        run: ./gradlew :closeGitHubMilestone $releaseGradleFlags

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator -v 1.13.2

      - name: Create GitHub Release
        run: ./gradlew :createGitHubRelease $releaseGradleFlags

      - name: Copy Signing secret key ring file
        run: sudo bash -c "echo '$SIGNING_SECRET_KEY_RING' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"

      - name: Publish on Sonatype
        run: ./gradlew publish $releaseGradleFlags

      - name: Publish on Gradle Plugins Portal
        run: ./gradlew publishPlugins -PGRADLE_PLUGIN_PORTAL_ENABLED=true $releaseGradleFlags

      - name: Close and Release Sonatype Repository
        run: ./gradlew closeAndReleaseRepository $releaseGradleFlags

      - name: Send merge pull request
        run: ./gradlew sendMergePullRequest --stacktrace
